name: Go Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'  # or your preferred Go version

      - name: Build the project
        run: go build

      - name: Create artifact file
        run: tar czvf mssql2csv.tar.gz mssql2csv *.sql

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: mssql2csv.tar.gz
          path: mssql2csv.tar.gz
